// <auto-generated />
using System;
using DocSystem.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocSystem.Models.AlszamCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IktatoszamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Next")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IktatoszamId")
                        .IsUnique();

                    b.ToTable("AlszamCounters");
                });

            modelBuilder.Entity("DocSystem.Models.FoszamCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IktatokonyvId")
                        .HasColumnType("uuid");

                    b.Property<int>("Next")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IktatokonyvId")
                        .IsUnique();

                    b.ToTable("FoszamCounters");
                });

            modelBuilder.Entity("DocSystem.Models.Iktatokonyv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Evszam")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Kod", "Evszam")
                        .IsUnique();

                    b.ToTable("Iktatokonyvek");
                });

            modelBuilder.Entity("DocSystem.Models.Iktatoszam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Alszam")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Foszam")
                        .HasColumnType("integer");

                    b.Property<Guid>("IktatokonyvId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IktatokonyvId", "Foszam", "Alszam")
                        .IsUnique();

                    b.ToTable("Iktatoszamok");
                });

            modelBuilder.Entity("DocSystem.Models.Irat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("IktatoszamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UgyiratId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IktatoszamId");

                    b.HasIndex("UgyiratId");

                    b.ToTable("Iratok");
                });

            modelBuilder.Entity("DocSystem.Models.Ugyirat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IktatoszamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IktatoszamId")
                        .IsUnique();

                    b.ToTable("Ugyiratok");
                });

            modelBuilder.Entity("DocSystem.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocSystem.Models.AlszamCounter", b =>
                {
                    b.HasOne("DocSystem.Models.Iktatoszam", "Iktatoszam")
                        .WithOne("AlszamCounter")
                        .HasForeignKey("DocSystem.Models.AlszamCounter", "IktatoszamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iktatoszam");
                });

            modelBuilder.Entity("DocSystem.Models.FoszamCounter", b =>
                {
                    b.HasOne("DocSystem.Models.Iktatokonyv", "Iktatokonyv")
                        .WithOne("FoszamCounter")
                        .HasForeignKey("DocSystem.Models.FoszamCounter", "IktatokonyvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iktatokonyv");
                });

            modelBuilder.Entity("DocSystem.Models.Iktatoszam", b =>
                {
                    b.HasOne("DocSystem.Models.Iktatokonyv", "Iktatokonyv")
                        .WithMany("Iktatoszamok")
                        .HasForeignKey("IktatokonyvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iktatokonyv");
                });

            modelBuilder.Entity("DocSystem.Models.Irat", b =>
                {
                    b.HasOne("DocSystem.Models.Iktatoszam", "Iktatoszam")
                        .WithMany()
                        .HasForeignKey("IktatoszamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocSystem.Models.Ugyirat", "Ugyirat")
                        .WithMany("Irats")
                        .HasForeignKey("UgyiratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iktatoszam");

                    b.Navigation("Ugyirat");
                });

            modelBuilder.Entity("DocSystem.Models.Ugyirat", b =>
                {
                    b.HasOne("DocSystem.Models.Iktatoszam", "Iktatoszam")
                        .WithOne()
                        .HasForeignKey("DocSystem.Models.Ugyirat", "IktatoszamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iktatoszam");
                });

            modelBuilder.Entity("DocSystem.Models.Iktatokonyv", b =>
                {
                    b.Navigation("FoszamCounter")
                        .IsRequired();

                    b.Navigation("Iktatoszamok");
                });

            modelBuilder.Entity("DocSystem.Models.Iktatoszam", b =>
                {
                    b.Navigation("AlszamCounter");
                });

            modelBuilder.Entity("DocSystem.Models.Ugyirat", b =>
                {
                    b.Navigation("Irats");
                });
#pragma warning restore 612, 618
        }
    }
}
